project:
  type: website
  output-dir: _output

# website
website:
  # basics
  title: "Python analytics accelerator"
  description: "A composable data system in a Python package."
  #favicon: logo.png
  search: false

  # options
  reader-mode: false
  twitter-card: true
  back-to-top-navigation: true
  repo-url: https://github.com/lostmygithubaccount/python-analytics-accelerator

  # footer
  page-footer:
    border: false
    center: "Python analytics accelerator"
    right:
      - icon: github
        href: https://github.com/lostmygithubaccount/python-analytics-accelerator

# theme
format:
  html:
    theme: minty
    toc: true
